/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "#e2e2e2",
        "surface-container-high": "#e8e8eb",
        "on-secondary": "#ffffff",
        "tertiary-fixed-dim": "#c6c6c6",
        "on-primary-container": "#848484",
        "primary-container": "#1b1b1b",
        "secondary-container": "#dfe0df",
        "surface-container-lowest": "#ffffff",
        "surface-bright": "#f9f9fc",
        "on-tertiary-fixed": "#1b1b1b",
        "outline": "#7e7576",
        "on-secondary-fixed-variant": "#454747",
        "inverse-on-surface": "#f0f0f3",
        "on-tertiary": "#ffffff",
        "on-error": "#ffffff",
        "primary-fixed-dim": "#c6c6c6",
        "surface-container-highest": "#e2e2e5",
        "on-tertiary-fixed-variant": "#474747",
        "surface": "#f9f9fc",
        "surface-container-low": "#f3f3f6",
        "inverse-surface": "#2f3033",
        "on-surface": "#1a1c1e",
        "on-secondary-fixed": "#1a1c1c",
        "on-primary-fixed": "#1b1b1b",
        "error": "#ba1a1a",
        "background": "#f9f9fc",
        "on-background": "#1a1c1e",
        "on-secondary-container": "#616362",
        "secondary-fixed-dim": "#c6c7c6",
        "tertiary-container": "#1b1b1b",
        "on-surface-variant": "#4c4546",
        "tertiary-fixed": "#e2e2e2",
        "surface-tint": "#5e5e5e",
        "primary-fixed": "#e2e2e2",
        "surface-variant": "#e2e2e5",
        "inverse-primary": "#c6c6c6",
        "on-primary-fixed-variant": "#474747",
        "secondary": "#5d5f5e",
        "surface-container": "#eeedf0",
        "primary": "#000000",
        "surface-dim": "#dadadd",
        "on-primary": "#ffffff",
        "on-tertiary-container": "#848484",
        "tertiary": "#000000",
        "on-error-container": "#93000a",
        "outline-variant": "#cfc4c5",
        "error-container": "#ffdad6",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        gutter: "24px",
        unit: "4px",
        "section-gap": "clamp(80px, 15vh, 160px)",
        "container-margin": "clamp(24px, 5vw, 64px)",
      },
      fontFamily: {
        "body-md": ["'Manrope'", "sans-serif"],
        "label-caps": ["'Manrope'", "sans-serif"],
        "display-xl": ["'Manrope'", "sans-serif"],
        "headline-lg": ["'Manrope'", "sans-serif"],
        "headline-md": ["'Manrope'", "sans-serif"],
        "body-lg": ["'Manrope'", "sans-serif"],
      },
      fontSize: {
        "body-md": ["1rem", { lineHeight: "1.5em", letterSpacing: "0em", fontWeight: "400" }],
        "label-caps": ["0.75rem", { lineHeight: "1em", letterSpacing: "0.1em", fontWeight: "700" }],
        "display-xl": ["clamp(3.5rem, 10vw, 8rem)", { lineHeight: "0.9em", letterSpacing: "-0.04em", fontWeight: "800" }],
        "headline-lg": ["clamp(2rem, 5vw, 3.5rem)", { lineHeight: "1.0em", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["1.5rem", { lineHeight: "1.1em", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-lg": ["1.125rem", { lineHeight: "1.4em", letterSpacing: "0em", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
}
